# Generated by Django 4.1.1 on 2022-09-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodlevels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='date_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bloodlevels.date'),
        ),
    ]
